"""Add file_url to notes

Revision ID: ef5d3595998c
Revises: 8c4223c1e61e
Create Date: 2025-02-15 21:13:46.287643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5d3595998c'
down_revision: Union[str, None] = '8c4223c1e61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('file_url', sa.String(), nullable=False))
    op.alter_column('notes', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_notes_filename', table_name='notes')
    op.create_unique_constraint(None, 'notes', ['filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='unique')
    op.create_index('ix_notes_filename', 'notes', ['filename'], unique=False)
    op.alter_column('notes', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('notes', 'file_url')
    # ### end Alembic commands ###
